### PR TITLE
fixed erase select feature

### PR DESCRIPTION
**Pull request by Geist5000**
Changed variable name

### CODE REVIEW

**Comment by Geist5000** [comment]
When will you update the binarys? I tried to compile it locally but I failed.

**Comment by isaacwisdom** [comment]
I should be able to get to that later today!

**Comment by isaacwisdom** [comment]
Hey! Sorry for the delay in making the new binaries. I recently upgraded to an M1 Mac and am still getting my development environment sorted out!

**Comment by isaacwisdom** [comment]
Hey, I finally managed to get my development environment sorted. Can you give the erase-select feature a try?

**Comment by Geist5000** [comment]
The fix works for me! I tested on a Remarkable 2 without any other extra software installed. 

Would you mind adding a small guide on how to build the v2 version? Like you did for v1?

Thanks, none the less.

**Pull request merged**
